import META from './meta.mjs';
import Validator from './validator.mjs';
import ModelError from './model-error.mjs';

import mongo from 'mongodb';

import assert from 'assert';
import util from 'util';
import { title } from 'process';
import { Console } from 'console';


/** 

All detected errors should be reported by throwing an array of
ModelError objects.  

Errors are of two types:

  + *Local errors* depend only on the field values of the current data
    item.  Local errors are specified and checked using meta.mjs
    and validator.mjs and are not specified below.

  + *Global errors* depend on data items other than the current data
    item.  The comments for the code below document global errors.

Each ModelError must be specified with an error code (defined below)
and an error message which should be as specific as possible.  If the
error is associated with a particular field, then the internal name of
that field should be filled in to the ModelError object.  Note that if
an error message refers to the name of the field, it should do so
using the external name (`label`) of the field.

The codes for the ModelError include the following:

BAD_ACT:
  Action does not correspond to one of the model action routines.

BAD_FIELD:
  An object contains an unknown field name or a forbidden field.

BAD_FIELD_VALUE:
  The value of a field does not meet its specs.

BAD_ID:
  Object not found for specified ID.  Includes an error when some field 
  specifies an id for some other object, but there is no object having
  that ID.

DB:
  Database error

FORM_ERROR:
  Form is invalid.

MISSING_FIELD:
  The value of a required field is not specified.

*/

export default class Model {

  /** Set up properties from props as properties of this. */
  constructor(props) {
    Object.assign(this, props);
  }

  /** Return a new instance of Model set up to use database specified
   *  by dbUrl
   */
  static async make(dbUrl) {
    let client;
    try {
      //@TODO
      client = await mongo.connect(dbUrl, MONGO_CONNECT_OPTIONS);

      const db = client.db(DB_NAME);
      const users = db.collection(Books_Catalog);
      const createCart = db.collection(CART);

      // return new Model({ client, users });
      const props = {
        validator: new Validator(META),
        conn: new Model({ client, users }),
        cartNew: new Model({ client, createCart })
      };
      const model = new Model(props);

      return model;
    }
    catch (err) {
      const msg = `cannot connect to URL "${dbUrl}": ${err}`;
      throw [new ModelError('DB', msg)];
    }
  }

  /** Release all resources held by this model.  Specifically,
   *  close any database connections.
   */
  async close() {
    //@TODO
    try {
      await this.conn.client.close();
    }
    catch (err) {
      const msg = `cannot connect to URL: ${err}`;
      throw [new ModelError('DB', msg)];
    }
  }

  /** Clear out all data stored within this model. */
  async clear() {
    //@TODO
    try {
      await this.conn.users.drop();
      await this.cartNew.createCart.drop();
    }
    catch (err) {
      const msg = `No Collection found: ${err}`;
      throw [new ModelError('BAD_ID', msg)];
    }
  }

  //Action routines

  /** Create a new cart.  Returns ID of newly created cart.  The
   * returned ID should not be generated by the database; it should
   * also not be easily guessable.
   *
   *  The new cart should have a `_lastModified` field set to the
   *  current Date timestamp.
   */
  async newCart(rawNameValues) {
    const nameValues = this._validate('newCart', rawNameValues);
    //@TODO

    let cartID = String(Math.random());
    try {
      await this.cartNew.createCart.insertOne({ _id: cartID })
    }
    catch (err) {

    }
    return cartID;
  }

  /** Given fields { cartId, sku, nUnits } = rawNameValues, update
   *  number of units for sku to nUnits.  Update `_lastModified` field
   *  of cart to current Date timestamp.
   *
   *  Global Errors:
   *    BAD_ID: cartId does not reference a cart.
   *            sku does not specify the isbn of an existing book.
   */
  async cartItem(rawNameValues) {
    const nameValues = this._validate('cartItem', rawNameValues);
    //@TODO

    const checkCartId = await this.cartNew.createCart.find({ _id: `${nameValues.cartId}` }).count();
    const checkifSKUPresent = await this.conn.users.find({ isbn: `${nameValues.sku}` }).count();
    if (checkCartId === 1 && checkifSKUPresent === 1) {
      const set = Object.assign({}, nameValues);
      const getSkuCount = await this.cartNew.createCart.find({ "cartItems.sku": `${nameValues.sku}` }).count()
      if (getSkuCount === 1 && nameValues.nUnits === 0) {
        const ret1 = await this.cartNew.createCart.updateOne({ _id: nameValues.cartId, "cartItems.sku": nameValues.sku }, { $currentDate: { _lastModified: true }, $pull: { 'cartItems': { 'sku': nameValues.sku } } })
      }
      else if (getSkuCount === 1) {
        const ret1 = await this.cartNew.createCart.updateOne({ _id: nameValues.cartId, "cartItems.sku": nameValues.sku }, { $currentDate: { _lastModified: true }, $set: { 'cartItems.$.nUnits': nameValues.nUnits } })
      }
      else if (nameValues.nUnits !== 0) {
        const ret = await this.cartNew.createCart.updateOne({ _id: nameValues.cartId }, { $currentDate: { _lastModified: true }, $push: { cartItems: { sku: nameValues.sku, nUnits: nameValues.nUnits } } }, { upsert: true });
      }
    }
    else {
      if (checkCartId === 0) {
        const msg = `no updates for cart "${nameValues.cartId}"`;
        throw [new ModelError(' BAD_ID', msg, 'cartId')];
      }
      else {
        const msg = `sku does not specify the isbn of an existing book: ${nameValues.sku}`;
        throw [new ModelError(' BAD_ID', msg, 'sku')];
      }

    }
  }

  /** Given fields { cartId } = nameValues, return cart identified by
   *  cartId.  The cart is returned as an object which contains a
   *  mapping from SKU's to *positive* integers (representing the
   *  number of units of the item identified by the SKU contained in
   *  the cart).  Addtionally, it must also have a `_lastModified`
   *  property containing a Date timestamp specifying the last time the
   *  cart was modified.
   *
   *  Globals Errors:
   *    BAD_ID: cartId does not reference a cart.
   */
  async getCart(rawNameValues) {
    const nameValues = this._validate('getCart', rawNameValues);

    //@TODO
    const check = await this.cartNew.createCart.find({ _id: `${nameValues.cartId}` }, { projection: { _id: 0 } }).toArray();
    var obj = {
      "_lastModified": check[0]._lastModified
    };

    check.forEach(element => {
      element.cartItems.forEach(ele => {
        obj[ele.sku] = ele.nUnits;
      });
    });

    if (check.length === 0) {
      const msg = `cartId does not reference a cart "${nameValues.cartId}"`;
      throw [new ModelError(' BAD_ID', msg, 'cartId')];
    }
    else
      return obj;
  }

  /** Given fields { isbn, title, authors, publisher, year, pages } =
   *  nameValues for a book, add the book to this model.  The isbn
   *  field should uniquely identify the book.  Note that if the book
   *  already exists in this model, then this routine should merely
   *  update the information associated with the book.
   *
   *  Returns the isbn of the added/updated book.
   *
   *  This routine should set a `_lastModified` field in the book to
   *  the current Date timestamp.
   */



  async addBook(rawNameValues) {
    const nameValues = this._validate('addBook', rawNameValues);
    //@TODO
    try {
      const set = Object.assign({}, nameValues);
      const ret = await this.conn.users.updateOne({ isbn: nameValues.isbn }, { $currentDate: { _lastModified: true }, $set: set }, { upsert: true });
      return nameValues.isbn;
    }
    catch (err) {
      return err
    }
  }


  /** Given fields { isbn, authorsTitle, _count=COUNT, _index=0 } =
   *  nameValues, retrieve list of all books with specified isbn (if
   *  any) and the words specified in authorsTitle occurring in either
   *  the book's authors field or the title field.  The retrieved
   *  results are sorted in ascending order by title.  The returned
   *  results have up to _count books starting at index _index in the
   *  retrieved results.  The `_index` and `_count` fields allow
   *  paging through the search results.
   *
   *  Will return [] if no books match the search criteria.
   */
  async findBooks(rawNameValues) {
    const nameValues = this._validate('findBooks', rawNameValues);
    //@TODO
    if (nameValues.hasOwnProperty('authorsTitleSearch')) {
      const ret = await this.conn.users.find({ title: { $regex: `${Object.values(nameValues)}` } })
      const retUsers = await ret.toArray();
      return [retUsers];
    }
    else if (nameValues.hasOwnProperty('isbn')) {
      const ret = await this.conn.users.find(nameValues)
      const retUsers = await ret.toArray();
      return [retUsers];
    }
  }

  //wrapper around this.validator to verify that no external field
  //is _id which is used by mongo
  _validate(action, rawNameValues) {
    let errs = [];
    let nameValues;
    try {
      nameValues = this.validator.validate(action, rawNameValues);
    }
    catch (err) {
      if (err instanceof Array) { //something we understand
        errs = err;
      }
      else {
        throw err; //not expected, throw upstairs
      }
    }
    if (rawNameValues._id !== undefined) {
      errs.push(new ModelError('BAD_FIELD', '_id field not permitted', '_id'));
    }
    if (errs.length > 0) throw errs;
    return nameValues;
  }


};

//use as second argument to mongo.connect()
const MONGO_CONNECT_OPTIONS = { useUnifiedTopology: true };

//default value for _count in findBooks()
const COUNT = 5;

//define private constants and functions here.
//const dbUrl = 'mongodb://localhost:27017';
const DB_NAME = "books"
const Books_Catalog = "booksCatalog"

//Shopping cart collection
const CART = "ShoppingCart"
